formatters:
  formatter:
    format: '%(asctime)s %(levelname)-8s %(name)s [%(funcName)s(%(module)s:%(lineno)s)]
      %(message)s'
handlers:
  console_handler:
    class: logging.StreamHandler
    formatter: formatter
    level: INFO
  file_handler:
    class: logging.FileHandler
    encoding: utf-8
    filename: log.txt
    formatter: formatter
    level: INFO
    mode: a
loggers:
  ? ''
  : handlers:
    - file_handler
    - console_handler
    level: DEBUG
version: 1
